"""add timestamps

Revision ID: 2dbe125b8db8
Revises: 6084e321b899
Create Date: 2021-02-18 17:37:07.173932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dbe125b8db8'
down_revision = '6084e321b899'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hosted_country', sa.Column('added_date', sa.DateTime(), nullable=True))
    op.add_column('hosted_country', sa.Column('last_seen_date', sa.DateTime(), nullable=True))
    op.add_column('hosted_country', sa.Column('removed_date', sa.DateTime(), nullable=True))
    op.add_column('resource_record', sa.Column('added_date', sa.DateTime(), nullable=True))
    op.add_column('resource_record', sa.Column('last_seen_date', sa.DateTime(), nullable=True))
    op.add_column('resource_record', sa.Column('removed_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource_record', 'removed_date')
    op.drop_column('resource_record', 'last_seen_date')
    op.drop_column('resource_record', 'added_date')
    op.drop_column('hosted_country', 'removed_date')
    op.drop_column('hosted_country', 'last_seen_date')
    op.drop_column('hosted_country', 'added_date')
    # ### end Alembic commands ###
